### ISSUE TITLE
ADAM can't build on Java 1.8

### ISSUE THREAD

**Issue by fnothaft** [bigdatagenomics/adam#198]
I am encountering the following error when building on Java 1.8:

```
[ERROR] An annotation processor threw an uncaught exception.
[ERROR] Consult the following stack trace for details.
[ERROR] java.lang.NoClassDefFoundError: com/sun/tools/javac/main/OptionName
[ERROR] 	at com.google.java.contract.core.apt.AnnotationProcessor.setupPaths(Unknown Source)
[ERROR] 	at com.google.java.contract.core.apt.AnnotationProcessor.init(Unknown Source)
[ERROR] 	at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:500)
[ERROR] 	at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:597)
[ERROR] 	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:690)
[ERROR] 	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
[ERROR] 	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
[ERROR] 	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
[ERROR] 	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1173)
[ERROR] 	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:859)
[ERROR] 	at com.sun.tools.javac.main.Main.compile(Main.java:523)
[ERROR] 	at com.sun.tools.javac.main.Main.compile(Main.java:381)
[ERROR] 	at com.sun.tools.javac.main.Main.compile(Main.java:370)
[ERROR] 	at com.sun.tools.javac.main.Main.compile(Main.java:361)
[ERROR] 	at com.sun.tools.javac.Main.compile(Main.java:56)
[ERROR] 	at com.sun.tools.javac.Main.main(Main.java:42)
[ERROR] Caused by: java.lang.ClassNotFoundException: com.sun.tools.javac.main.OptionName
[ERROR] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
[ERROR] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
[ERROR] 	at java.security.AccessController.doPrivileged(Native Method)
[ERROR] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
[ERROR] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[ERROR] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[ERROR] 	... 16 more
```

I believe the error may be coming from [Cofoja](https://groups.google.com/forum/#!topic/cofoja/3q8Ol5nVnOY).

**Comment by heuermh** [comment]
I believe this issue can be closed by #540
